#!/usr/bin/env python3
"""Generate static/service-icons.js from Simple Icons (CC0 icon data).

    python3 tools/make_service_icons.py <path to simple-icons package>

Only an allowlist of brands is included: those still in Simple Icons and
without known restrictions on third parties showing their logo to identify
the service. Brands that restrict this (e.g. Apple, Google, Meta, Microsoft,
Amazon) keep KeyMelier's letter avatar. Logos are trademarks of their owners
and are used unmodified, only to identify the service, and bundled – no icon
is ever fetched from the network.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# KeyMelier service key -> Simple Icons slug
ALLOW = {
    "github": "github", "gitlab": "gitlab", "bitwarden": "bitwarden", "1password": "1password",
    "proton": "proton", "cloudflare": "cloudflare", "atlassian": "atlassian", "npm": "npm", "npmjs": "npm",
    "pypi": "pypi", "docker": "docker", "hetzner": "hetzner", "discord": "discord", "okta": "okta",
    "yubico": "yubico", "mastodon": "mastodon", "tailscale": "tailscale", "vercel": "vercel",
    "netlify": "netlify", "digitalocean": "digitalocean", "dropbox": "dropbox", "stripe": "stripe",
    "paypal": "paypal", "ebay": "ebay", "shopify": "shopify", "coinbase": "coinbase", "binance": "binance",
    "zoho": "zoho", "hubspot": "hubspot", "mailchimp": "mailchimp", "ionos": "ionos", "n26": "n26",
    "webauthn": "webauthn",
}


def main(package: Path):
    meta = json.loads((package / "package.json").read_text())
    icons = {}
    for key, slug in ALLOW.items():
        svg = (package / "icons" / f"{slug}.svg").read_text()
        path = re.search(r'<path d="([^"]+)"', svg).group(1)
        title = re.search(r"<title>([^<]+)</title>", svg).group(1)
        data = json.loads((package / "data" / "simple-icons.json").read_text())
        entries = data if isinstance(data, list) else data.get("icons", [])
        hexcolor = next((e["hex"] for e in entries if e.get("slug") == slug
                         or re.sub(r"[^a-z0-9]", "", e["title"].lower()) == slug), "444444")
        icons[key] = {"title": title, "hex": hexcolor, "path": path}
    out = ROOT / "static" / "service-icons.js"
    out.write_text(
        "// Generated by tools/make_service_icons.py from Simple Icons "
        f"{meta['version']} (CC0-1.0 icon data).\n"
        "// Logos are trademarks of their owners, shown unmodified only to identify the service.\n"
        f"const SERVICE_ICONS = {json.dumps(icons, separators=(',', ':'))};\n",
        encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(icons)} services, {out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
