"""Build docs/hardware.html (public hardware test matrix) from HARDWARE_TESTS.md.

    python3 tools/make_hardware_page.py          write the page
    python3 tools/make_hardware_page.py --check  exit 1 if the page is out of date

HARDWARE_TESTS.md stays the single source; this only renders its matrix for
the website.
"""

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "HARDWARE_TESTS.md"
TARGET = ROOT / "docs" / "hardware.html"

HEADERS = ["Operating system", "KeyMelier", "Key model", "Firmware", "Detection", "Read functions",
           "Cancel & reconnect", "Result", "Date, notes"]
STATUS = {"Passed": "ok", "Failed": "fail", "Not supported": "none", "Not tested": "open"}
ISSUE = "https://github.com/FiraSenax/KeyMelier/issues/new?template=tested-with.yml"
SOURCE_URL = "https://github.com/FiraSenax/KeyMelier/blob/main/HARDWARE_TESTS.md"


def matrix_rows(md: str) -> list[list[str]]:
    lines = md[md.index("## Matrix"):].splitlines()
    table = [l for l in lines if l.startswith("|")]
    rows = [[c.strip() for c in l.strip().strip("|").split("|")] for l in table[2:]]
    return [r for r in rows if len(r) == len(HEADERS)]


def cell(text: str) -> str:
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    status = next((cls for word, cls in STATUS.items() if text.startswith(word)), None)
    body = html.escape(text) or "–"
    return f'<td><span class="st {status}">{body}</span></td>' if status else f"<td>{body}</td>"


def render() -> str:
    rows = matrix_rows(SOURCE.read_text(encoding="utf-8"))
    results = [r[7] for r in rows]
    tested = sum(1 for r in results if not r.startswith("Not tested"))
    body = "\n".join("<tr>" + "".join(cell(c) for c in r) + "</tr>" for r in rows)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>KeyMelier – tested security keys</title>
<meta name="description" content="Which security keys KeyMelier was tested with, on which system, and what worked.">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'self'; base-uri 'none'; form-action 'none'">
<link rel="icon" href="icon.svg" type="image/svg+xml">
<!-- Generated by tools/make_hardware_page.py from HARDWARE_TESTS.md – do not edit by hand. -->
<style>
  :root {{ --bg: #f6f5f2; --card: #fff; --text: #1d1b20; --muted: #5d5a63; --line: #e3e0da; --accent: #7a1f3d;
          --ok: #1f7a45; --fail: #b3261e; --open: #6b6770; }}
  @media (prefers-color-scheme: dark) {{ :root {{ --bg: #141217; --card: #1d1a21; --text: #f1eef4; --muted: #aaa4b1;
          --line: #2f2a35; --accent: #e0789c; --ok: #5fd38d; --fail: #ff8a80; --open: #aaa4b1; }} }}
  body {{ margin: 0; background: var(--bg); color: var(--text); font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }}
  main {{ max-width: 1180px; margin: 0 auto; padding: 32px 20px 64px; }}
  a {{ color: var(--accent); }}
  h1 {{ margin: 0 0 6px; }}
  .wrap {{ overflow-x: auto; border: 1px solid var(--line); border-radius: 12px; background: var(--card); }}
  table {{ border-collapse: collapse; width: 100%; font-size: 0.9rem; }}
  th, td {{ padding: 8px 10px; border-bottom: 1px solid var(--line); text-align: left; vertical-align: top; }}
  th {{ font-size: 0.8rem; color: var(--muted); white-space: nowrap; }}
  .st {{ font-weight: 600; }} .st.ok {{ color: var(--ok); }} .st.fail {{ color: var(--fail); }} .st.open, .st.none {{ color: var(--open); }}
  .note {{ color: var(--muted); }}
</style>
</head>
<body>
<main>
  <p><a href="index.html">KeyMelier</a> · <a href="guide.html">Documentation</a></p>
  <h1>Tested security keys</h1>
  <p>Which keys KeyMelier was tested with by hand, on which system, and what worked. {tested} of {len(rows)} combinations have a result;
  <b>Not tested</b> means nobody has reported it yet – it does not mean it fails. Every FIDO2 key should be detected;
  what a specific key can do is shown in the app under <i>What this key can do</i>.</p>
  <p><a href="{ISSUE}">Report your key</a> (a short form, without serial numbers or account names) ·
  <a href="{SOURCE_URL}">How to test and the rules</a></p>
  <div class="wrap"><table>
    <thead><tr>{"".join(f"<th>{h}</th>" for h in HEADERS)}</tr></thead>
    <tbody>
{body}
    </tbody>
  </table></div>
  <p class="note">Results are only listed when their origin is known; automated tests (see TESTING.md) do not count as hardware results.</p>
</main>
</body>
</html>
"""


def main() -> int:
    page = render()
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != page:
            print("docs/hardware.html is out of date – run: python3 tools/make_hardware_page.py")
            return 1
        print("docs/hardware.html is up to date")
        return 0
    TARGET.write_text(page, encoding="utf-8")
    print(TARGET.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
